In [3]:

import os
import pandas
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from datetime import datetime
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from matplotlib import pyplot
from sklearn.metrics import accuracy_score
import random

path = os.path.join(os.getcwd(), "smoke_detection_iot.csv")
dataset = pandas.read_csv(path)

dataset.head()

,Unnamed: 0,UTC,Temperature[C],Humidity[%],TVOC[ppb],eCO2[ppm],Raw H2,Raw Ethanol,Pressure[hPa],PM1.0,PM2.5,NC0.5,NC1.0,NC2.5,CNT,Fire Alarm
0,0,1654733331,20.000,57.36,0,400,12306,18520,939.735,0.0,0.0,0.0,0.0,0.0,0,0
1,1,1654733332,20.015,56.67,0,400,12345,18651,939.744,0.0,0.0,0.0,0.0,0.0,1,0
2,2,1654733333,20.029,55.96,0,400,12374,18764,939.738,0.0,0.0,0.0,0.0,0.0,2,0
3,3,1654733334,20.044,55.28,0,400,12390,18849,939.736,0.0,0.0,0.0,0.0,0.0,3,0
4,4,1654733335,20.059,54.69,0,400,12403,18921,939.744,0.0,0.0,0.0,0.0,0.0,4,0

In [4]:
dataset = dataset.drop(columns=['Unnamed: 0', 'UTC'])
dataset = dataset.sample(frac=1)

In [5]:

X_train, X_test, y_train, y_test = train_test_split(dataset.drop(columns=['Fire Alarm']), dataset['Fire Alarm'], test_size=0.33, shuffle=1, random_state=42)

In [6]:

model = DecisionTreeClassifier(max_depth=6)

model.fit(X_train, y_train)

pred_train = model.predict(X_train)
pred_test = model.predict(X_test)

print("Training", accuracy_score(y_train, pred_train) * 100)
print("Testing", accuracy_score(y_test, pred_test) * 100)

Training 99.99285067441971
Testing 99.98548480743177